export default {
    key: process.env.KEY,
    newKey: process.env.NEW_KEY,
    passwordAccess: process.env.PASSWORD_ACCESS,
    passwordRefresh: process.env.PASSWORD_REFRESH,
    passwordCookie: process.env.PASSWORD_COOKIE,
    createAcctBlocked: process.env.BLOCK_CREATE_ACCOUNT,
    root: process.env.ROOT,
    url: process.env.URL,
    mongoURL: process.env.MONGODB_URL,
    dbType: process.env.DB_TYPE,
    fsDirectory: process.env.FS_DIRECTORY,
    s3ID: process.env.S3_ID,
    s3Key: process.env.S3_KEY,
    s3Bucket: process.env.S3_BUCKET,
    useDocumentDB: process.env.USE_DOCUMENT_DB,
    documentDBBundle: process.env.DOCUMENT_DB_BUNDLE,
    sendgridKey: process.env.SENDGRID_KEY,
    sendgridEmail: process.env.SENDGRID_EMAIL,
    remoteURL: process.env.REMOTE_URL,
    disableEmailVerification: process.env.DISABLE_EMAIL_VERIFICATION,
    secureCookies: process.env.SECURE_COOKIES
}

module.exports = {
    key: process.env.KEY,
    newKey: process.env.NEW_KEY,
    passwordAccess: process.env.PASSWORD_ACCESS,
    passwordRefresh: process.env.PASSWORD_REFRESH,
    passwordCookie: process.env.PASSWORD_COOKIE,
    createAcctBlocked: process.env.BLOCK_CREATE_ACCOUNT,
    root: process.env.ROOT,
    url: process.env.URL,
    mongoURL: process.env.MONGODB_URL,
    dbType: process.env.DB_TYPE,
    fsDirectory: process.env.FS_DIRECTORY,
    s3ID: process.env.S3_ID,
    s3Key: process.env.S3_KEY,
    s3Bucket: process.env.S3_BUCKET,
    useDocumentDB: process.env.USE_DOCUMENT_DB,
    documentDBBundle: process.env.DOCUMENT_DB_BUNDLE,
    sendgridKey: process.env.SENDGRID_KEY,
    sendgridEmail: process.env.SENDGRID_EMAIL,
    remoteURL: process.env.REMOTE_URL,
    disableEmailVerification: process.env.DISABLE_EMAIL_VERIFICATION,
    secureCookies: process.env.SECURE_COOKIES
}